
import java.io.BufferedReader;
import java.io.InputStreamReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Himanshu
 */
public class gui extends javax.swing.JFrame {
    public static void runSystemCommand(String command) {

		try {
			Process p = Runtime.getRuntime().exec(command);
			BufferedReader inputStream = new BufferedReader(
					new InputStreamReader(p.getInputStream()));

			String s = "";
			// reading output stream of the command
			while ((s = inputStream.readLine()) != null) {
				System.out.println(s);
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        path = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        attacktype = new javax.swing.JLabel();
        hashtype = new javax.swing.JLabel();
        passpattern = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        workload = new javax.swing.JLabel();
        eightdigit = new javax.swing.JRadioButton();
        tendigit = new javax.swing.JRadioButton();
        hash = new javax.swing.JRadioButton();
        attack = new javax.swing.JRadioButton();
        low = new javax.swing.JRadioButton();
        def = new javax.swing.JRadioButton();
        high = new javax.swing.JRadioButton();
        nightmare = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HASHCAT GUI");

        path.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        path.setText("CHANGE YOUR HCCAPX FILR NAME TO test.haccapx AND PASTE IT TO C:\\hascat DIRECTORY");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        attacktype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attacktype.setText("CHOOSE THE ATTACK TYPE");

        hashtype.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hashtype.setText("CHOOSE THE HASHTYPE");

        passpattern.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passpattern.setText("CHOOSE PASSWORD PATTERN");

        workload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        workload.setText("CHOOSE THE WORK LOAD");

        eightdigit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eightdigit.setText("8 DIGIT PASS");
        eightdigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightdigitActionPerformed(evt);
            }
        });

        tendigit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tendigit.setText("10 DIGIT PASS");
        tendigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tendigitActionPerformed(evt);
            }
        });

        hash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hash.setText("SELECT THIS IF YOU HAVE GIVEN HCCAPX FILE");

        attack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attack.setText("SELECT THIS IF YOU WANT TO BRUTE FORCE");
        attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackActionPerformed(evt);
            }
        });

        low.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        low.setText("LOW");

        def.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        def.setText("DEFAULT");
        def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defActionPerformed(evt);
            }
        });

        high.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        high.setText("HIGH");

        nightmare.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nightmare.setText("NIGHTMARE");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("DICTIONERY ATTACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attacktype)
                                    .addComponent(hashtype)
                                    .addComponent(workload))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attack)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tendigit)
                                        .addGap(73, 73, 73)
                                        .addComponent(eightdigit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(hash))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(low)
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nightmare)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(def)
                                                .addGap(30, 30, 30)
                                                .addComponent(high))))))
                            .addComponent(jLabel5))
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(path)
                            .addComponent(passpattern))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1)
                        .addGap(68, 68, 68)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(path)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attacktype)
                    .addComponent(attack))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hashtype)
                    .addComponent(hash))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passpattern)
                    .addComponent(eightdigit)
                    .addComponent(tendigit))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workload)
                    .addComponent(low)
                    .addComponent(def)
                    .addComponent(high))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(nightmare)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if ((tendigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (low.isSelected()==true))
{
 try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"tendigitw1\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((eightdigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (low.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"eightdigitw1\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((tendigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (def.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"tendigitw2\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((tendigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (high.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"tendigitw3\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((tendigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (nightmare.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"tendigitw4\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((eightdigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (def.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"eightdigitw2\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((eightdigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (high.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"eightdigitw3\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if ((eightdigit.isSelected()==true) && (attack.isSelected()==true) && (hash.isSelected()==true) && (nightmare.isSelected()==true))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"eightdigitw4\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}
else if((eightdigit.isSelected()==false) || (attack.isSelected()==false) || (hash.isSelected()==false) || (low.isSelected()==false))
{
    try
        {  
         // We are running "dir" and "ping" command on cmd 
         Runtime.getRuntime().exec("cmd /c start cmd.exe /K \"help\""); 
        } 
        catch (Exception e) 
        { 
            System.out.println("HEY Buddy ! U r Doing Something Wrong "); 
            e.printStackTrace(); 
        }
}






// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eightdigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightdigitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightdigitActionPerformed

    private void tendigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tendigitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tendigitActionPerformed

    private void attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attackActionPerformed

    private void defActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Dictionery dec=new Dictionery();
dec.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton attack;
    private javax.swing.JLabel attacktype;
    private javax.swing.JRadioButton def;
    private javax.swing.JRadioButton eightdigit;
    private javax.swing.JRadioButton hash;
    private javax.swing.JLabel hashtype;
    private javax.swing.JRadioButton high;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton low;
    private javax.swing.JRadioButton nightmare;
    private javax.swing.JLabel passpattern;
    private javax.swing.JLabel path;
    private javax.swing.JRadioButton tendigit;
    private javax.swing.JLabel workload;
    // End of variables declaration//GEN-END:variables
}
